### ISSUE TITLE
Datepicker problems

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#3] opened 2015-11-12 08:08 UTC
Hi,

I have just tried to use datepicker control, but it is not working correctly. 
It initialises OK, but when I open datepick dropdown, table for days is not working properly. 

In my project I have a table of case items where I have two dates to set in each row. HTML is generated in javascript in for-each loop where each input DOM element get it's own unique name like: 'install-'+index. 
When opening datepick dropdown in table with few rows dropdown is not whole visible, but it is cut off at the end of the table. (html for datepick is put into <td> of a table). 
Second thing is, that when I get with mouse over days table row containing that day expands to the right a bit making whole row kinda "sticking" out of dropdown. 
If there is more info needed I will provide the code. :)

One more thing: I used onchange() function before on my <input> elements, but now it seems not to work when changing date with datepicker. Would be nice to have fired this event as well because sometimes there is situation that another input field has to be updated or filled with some data when date is changed no matter which way (via dropdown or being typed in). 

P.P.S.: When I click into one input dropdown is shown, but when I click into another input with datepicker another dropdown is shown and previous is not closed. Is there an option to get dropdown closed when element loses focus?

**Comment by djlimbs** [comment] 2015-11-12 15:25
Hi,

We will need more info (code samples, screenshots) to duplicate and investigate your issue with datepicker inputs inside a table.

We will note your request and bug about closing datepickers. In the future, please add these as separate issues so that we can properly track them. Thank you.

**Comment by matejp84** [comment] 2015-11-13 10:54
Ok here it is:
On page I fill in data for each row and table cell in for each loop. Each content is generated as string and then appended into correct table row:

`text += '<td data-label=""><div class="slds-form-element"><div class="slds-form-element__control"><div class="slds-input-has-icon slds-input-has-icon--right"><svg aria-hidden="true" class="slds-input__icon slds-icon-text-default"><use xlink:href="{!URLFOR($Resource.SLDS0102,'assets/icons/utility-sprite/svg/symbols.svg#event')}"></use></svg><input id="install-'+item+'" onchange="changeInstallDate(this);" class="slds-input" type="text" placeholder="Install Date"></div></div></div></td>';`
datepicker is initialized jsut few code of lines below as: 
`$("#install-" + item).datepicker({ format: 'DD.MM.YYYY' }).val(caseItems[item].installDate);`

And here is the image what is wrong:
http://shrani.si/f/41/yx/1A96nm5p/screen-shot-2015-11-13-a.png
2 things:
- multiple datepickers can opened up. Probably this isn't the bug, but maybe it would be nice to auto-close datepicker if input loses focus? 
- as you can see datepicker rows are going out of dropdown (visually)

Thanks for your help! :)

**Comment by djlimbs** [comment] 2015-11-13 15:29
Thanks for the info -
We were able to reproduce the the row visual problem by moving standard SLDS datepicker markup into a <td>. It looks like from your screenshot that certain SLDS css is not correctly being applied to the datepicker (I do not see left/right icons around the month, and the year dropdown's style also does not match SLDS styles). We believe this is an issue with the SLDS css, so please open an issue about this in their repo.

For your second point, 0.1.1 addressed multiple datepickers being open. Opening another datepicker closes any other in the DOM. We are working on a hot-fix related to those code changes regarding typing user input into the datepicker. If you run into this issue again, please open a separate issue so we can track it better.

About your datepicker initialize call, I noticed you chain the method with "val" to add an initial date. I recommend you initialize the date using the "initDate" option, which accepts a moment object. This will ensure better state tracking with the datepicker. More documentation about datepicker options is available here: http://aljs.appiphony.com/#!/datepickers

**Closed** 2015-11-13 15:29 UTC
